apiVersion: v1
data:
  dbPassword: amFuc3UxMjM=
  dbUsername: ZGlzY291cnNl
  smtpPassword: MXFheiFRQVoyd3N4QFdTWA==
  smtpUsername: ZGJuZXN0LXJvYm90QG1haWwuZGJuZXN0Lm5ldA==
kind: Secret
metadata:
  creationTimestamp: null
  name: secret
