apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discourse-ingress
spec:
  rules:
  - host: www.dbnest.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-server
            port:
              name: http
  tls:
  - hosts:
    - www.dbnest.net
