apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-postgres
  local:
    path: /Users/jan/Database/k8s/discourse/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-postgres
  labels:
    app: pgsql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage-postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-sharedssd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-sharedssd
  local:
    path: /Users/jan/Database/k8s/discourse/data/sharedssd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-sharedssd
  labels:
    app: web-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage-sharedssd